// <auto-generated />
using MarlonApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MarlonApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("MarlonApi.Models.TodoStudent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("BSEducationSchool");

                    b.Property<string>("BSEducationTitle");

                    b.Property<string>("Email");

                    b.Property<string>("ExtraCurricularActivitiesOne");

                    b.Property<string>("ExtraCurricularActivitiesTwo");

                    b.Property<string>("MSEducationSchool");

                    b.Property<string>("MSEducationTitle");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PHdEducationSchool");

                    b.Property<string>("PHdEducationTitle");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("WorkExperienceCompanyNameOne");

                    b.Property<string>("WorkExperienceCompanyNameThree");

                    b.Property<string>("WorkExperienceCompanyNameTwo");

                    b.Property<string>("WorkExperienceTitleOne");

                    b.Property<string>("WorkExperienceTitleThree");

                    b.Property<string>("WorkExperienceTitleTwo");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
